import type {
  PlatformConnection,
  PostType,
  ScheduledPost,
  DashboardMetrics,
  WorkflowLog,
  IntegrationStatus,
} from '@smm/shared';
export const mockConnections: PlatformConnection[] = [
  {
    id: '1',
    userId: 'u1',
    platformId: 'x',
    status: 'active',
    platformUsername: '@masonsabin',
    connectedAt: new Date('2024-01-15'),
    lastRefreshedAt: new Date(),
  },
  {
    id: '2',
    userId: 'u1',
    platformId: 'linkedin',
    status: 'active',
    platformUsername: 'Mason Sabin',
    connectedAt: new Date('2024-01-20'),
    lastRefreshedAt: new Date(),
  },
  {
    id: '3',
    userId: 'u1',
    platformId: 'instagram',
    status: 'expired',
    platformUsername: '@masonsabin',
    connectedAt: new Date('2024-02-01'),
    lastRefreshedAt: new Date('2024-05-01'),
  },
  {
    id: '4',
    userId: 'u1',
    platformId: 'facebook',
    status: 'disconnected',
    platformUsername: '',
    connectedAt: new Date('2024-01-01'),
    lastRefreshedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    userId: 'u1',
    platformId: 'threads',
    status: 'disconnected',
    platformUsername: '',
    connectedAt: new Date('2024-01-01'),
    lastRefreshedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    userId: 'u1',
    platformId: 'tiktok',
    status: 'disconnected',
    platformUsername: '',
    connectedAt: new Date('2024-01-01'),
    lastRefreshedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    userId: 'u1',
    platformId: 'bluesky',
    status: 'active',
    platformUsername: '@masonsabin.bsky.social',
    connectedAt: new Date('2024-03-10'),
    lastRefreshedAt: new Date(),
  },
];
export const mockPostTypes: PostType[] = [
  {
    id: 'business',
    userId: 'u1',
    name: 'Business Forward',
    isDefault: true,
    targetPlatforms: ['linkedin', 'x'],
    toneDescriptor: 'Professional, thought-leadership, data-driven',
    formattingPreferences: {
      useEmojis: false,
      hashtagStyle: 'minimal',
      linkPlacement: 'end',
      mentionStyle: 'formal',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'personal',
    userId: 'u1',
    name: 'Personal',
    isDefault: true,
    targetPlatforms: ['x', 'instagram', 'bluesky', 'facebook', 'tiktok'],
    toneDescriptor: 'Casual, authentic, conversational',
    formattingPreferences: {
      useEmojis: true,
      hashtagStyle: 'moderate',
      linkPlacement: 'inline',
      mentionStyle: 'casual',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
export const mockPosts: ScheduledPost[] = [
  {
    id: 'p1',
    userId: 'u1',
    postTypeId: 'business',
    originalContent:
      'Excited to share our latest insights on AI-driven social media strategy. The results speak for themselves.',
    adaptedContent: {},
    targetPlatforms: ['linkedin', 'x'],
    status: 'published',
    scheduledAt: new Date('2026-05-30T10:00:00'),
    publishedAt: new Date('2026-05-30T10:00:00'),
    platformPostIds: { linkedin: 'li_123', x: 'x_456' },
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date('2026-05-29'),
    updatedAt: new Date('2026-05-30'),
  },
  {
    id: 'p2',
    userId: 'u1',
    postTypeId: 'personal',
    originalContent: 'Beautiful morning hike today. Nature recharges everything.',
    adaptedContent: {},
    targetPlatforms: ['x', 'instagram', 'bluesky'],
    status: 'scheduled',
    scheduledAt: new Date('2026-06-03T08:00:00'),
    platformPostIds: {},
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date('2026-06-02'),
    updatedAt: new Date('2026-06-02'),
  },
  {
    id: 'p3',
    userId: 'u1',
    postTypeId: 'business',
    originalContent: 'Key takeaways from this week in tech — thread incoming.',
    adaptedContent: {},
    targetPlatforms: ['linkedin', 'x'],
    status: 'draft',
    platformPostIds: {},
    retryCount: 0,
    maxRetries: 3,
    createdAt: new Date('2026-06-02'),
    updatedAt: new Date('2026-06-02'),
  },
];
export const mockDashboardMetrics: DashboardMetrics = {
  period: { from: new Date('2026-05-01'), to: new Date('2026-06-01') },
  aggregate: {
    totalLikes: 1847,
    totalShares: 342,
    totalComments: 218,
    totalImpressions: 48320,
    byPlatform: {
      linkedin: {
        likes: 923,
        shares: 210,
        comments: 145,
        impressions: 21400,
        platform: 'linkedin',
        collectedAt: new Date(),
      },
      x: {
        likes: 724,
        shares: 112,
        comments: 63,
        impressions: 19200,
        platform: 'x',
        collectedAt: new Date(),
      },
      bluesky: {
        likes: 200,
        shares: 20,
        comments: 10,
        impressions: 7720,
        platform: 'bluesky',
        collectedAt: new Date(),
      },
    },
  },
  topPosts: [],
  engagementByDay: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(2026, 4, i + 1),
    likes: Math.floor(40 + Math.random() * 80),
    shares: Math.floor(5 + Math.random() * 20),
    comments: Math.floor(3 + Math.random() * 15),
    impressions: Math.floor(800 + Math.random() * 1200),
  })),
};
export const mockWorkflowLogs: WorkflowLog[] = [
  {
    id: 'wf1',
    userId: 'u1',
    instruction: 'Create a week of business-forward posts about AI trends',
    status: 'completed',
    steps: [
      {
        stepId: 's1',
        type: 'plan',
        description: 'Decompose into 5 daily posts with unique angles',
        input: { instruction: 'Create a week of business-forward posts about AI trends' },
        output: { planSteps: 5 },
        status: 'success',
        timestamp: new Date('2026-06-01T09:00:00'),
        durationMs: 820,
      },
      {
        stepId: 's2',
        type: 'tool_use',
        description: 'Research trending AI topics via Apify',
        input: { query: 'AI trends 2026' },
        output: { topics: ['agentic AI', 'multimodal models', 'inference efficiency'] },
        status: 'success',
        timestamp: new Date('2026-06-01T09:00:01'),
        durationMs: 2100,
      },
      {
        stepId: 's3',
        type: 'tool_use',
        description: 'Generate 5 draft posts via Cerebras',
        input: { count: 5, tone: 'business-forward' },
        output: { draftsCreated: 5 },
        status: 'success',
        timestamp: new Date('2026-06-01T09:00:03'),
        durationMs: 3400,
      },
      {
        stepId: 's4',
        type: 'reflection',
        description: 'Verify all posts meet LinkedIn 3000-char limit',
        input: { drafts: 5 },
        output: { valid: 5, invalid: 0 },
        status: 'success',
        timestamp: new Date('2026-06-01T09:00:07'),
        durationMs: 410,
      },
    ],
    startedAt: new Date('2026-06-01T09:00:00'),
    completedAt: new Date('2026-06-01T09:00:08'),
    summary: 'Created 5 business-forward posts scheduled Mon–Fri targeting LinkedIn and X.',
  },
];
export const mockIntegrations: IntegrationStatus[] = [
  { id: 'vapi', name: 'Vapi Voice AI', configured: false },
  { id: 'apify', name: 'Apify Web Scraping', configured: true, lastUsed: new Date('2026-06-01') },
];
